import {
  AlignmentType,
  Document,
  Footer,
  HeadingLevel,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { ExecutiveSummary, CellValue } from '@afdip/shared';

export interface DocumentData {
  fileName: string;
  projectName: string;
  language: 'ar' | 'en';
  summary: ExecutiveSummary | null;
  tables: Array<{
    sheetName: string;
    range: string;
    statementType: string | null;
    headers: string[];
    rows: CellValue[][];
  }>;
  findings: Array<{
    severity: string;
    message: string;
    messageAr: string;
    sheetName: string | null;
    cell: string | null;
  }>;
  style: {
    brandColor: string;
    fontLatin: string;
    fontArabic: string;
    includeCover: boolean;
    includeValidationReport: boolean;
  };
}

const SEVERITY_COLORS: Record<string, string> = {
  error: 'C0392B',
  warning: 'B9770E',
  info: '2471A3',
};

const L = {
  ar: {
    generatedBy: 'أُنشئ بواسطة منصة الذكاء الاصطناعي لتحليل المستندات المالية',
    executiveSummary: 'الملخص التنفيذي',
    keyFigures: 'أهم المؤشرات',
    detectedTables: 'الجداول المكتشفة',
    validationReport: 'تقرير التحقق المالي',
    sheet: 'الورقة',
    range: 'النطاق',
    severity: 'الخطورة',
    location: 'الموقع',
    finding: 'الملاحظة',
    project: 'المشروع',
    noFindings: 'لم تُرصد أي ملاحظات — النموذج سليم وفق القواعد المفعّلة.',
    severityName: { error: 'خطأ', warning: 'تحذير', info: 'معلومة' } as Record<string, string>,
  },
  en: {
    generatedBy: 'Generated by the AI Financial Document Intelligence Platform',
    executiveSummary: 'Executive Summary',
    keyFigures: 'Key Figures',
    detectedTables: 'Detected Tables',
    validationReport: 'Financial Validation Report',
    sheet: 'Sheet',
    range: 'Range',
    severity: 'Severity',
    location: 'Location',
    finding: 'Finding',
    project: 'Project',
    noFindings: 'No findings — the model passes all active rules.',
    severityName: { error: 'Error', warning: 'Warning', info: 'Info' } as Record<string, string>,
  },
};

export async function buildDocx(data: DocumentData): Promise<Buffer> {
  const ar = data.language === 'ar';
  const t = L[data.language];
  const font = ar ? data.style.fontArabic : data.style.fontLatin;
  const align = ar ? AlignmentType.RIGHT : AlignmentType.LEFT;

  const p = (
    text: string,
    opts: { heading?: (typeof HeadingLevel)[keyof typeof HeadingLevel]; bold?: boolean; size?: number; color?: string } = {},
  ): Paragraph =>
    new Paragraph({
      heading: opts.heading,
      alignment: opts.heading ? align : align,
      bidirectional: ar,
      children: [
        new TextRun({
          text,
          bold: opts.bold,
          size: opts.size,
          color: opts.color,
          font,
          rightToLeft: ar,
        }),
      ],
    });

  const children: (Paragraph | Table)[] = [];

  const title = ar
    ? data.summary?.titleAr ?? `تقرير التحليل المالي — ${data.fileName}`
    : data.summary?.title ?? `Financial Analysis Report — ${data.fileName}`;

  if (data.style.includeCover) {
    children.push(
      new Paragraph({ spacing: { before: 2400 }, children: [] }),
      p(title, { heading: HeadingLevel.TITLE }),
      p(`${t.project}: ${data.projectName}`, { bold: true }),
      p(data.fileName),
      p(t.generatedBy, { color: '888888' }),
      new Paragraph({ pageBreakBefore: false, children: [] }),
    );
  }

  // Executive summary
  if (data.summary) {
    children.push(p(t.executiveSummary, { heading: HeadingLevel.HEADING_1 }));
    const paragraphs = ar ? data.summary.paragraphsAr : data.summary.paragraphs;
    for (const para of paragraphs) children.push(p(para));

    if (data.summary.keyFigures.length) {
      children.push(p(t.keyFigures, { heading: HeadingLevel.HEADING_2 }));
      children.push(
        buildTable(
          [ar ? 'المؤشر' : 'Figure', ar ? 'القيمة' : 'Value'],
          data.summary.keyFigures.map((f) => [
            ar ? f.labelAr : f.label,
            f.value.toLocaleString(ar ? 'ar-EG' : 'en-US'),
          ]),
          data.style.brandColor,
          font,
          ar,
        ),
      );
    }
  }

  // Detected tables
  children.push(p(t.detectedTables, { heading: HeadingLevel.HEADING_1 }));
  for (const table of data.tables) {
    const label = `${t.sheet}: ${table.sheetName} — ${t.range}: ${table.range}` +
      (table.statementType && table.statementType !== 'other' ? ` (${table.statementType})` : '');
    children.push(p(label, { heading: HeadingLevel.HEADING_2 }));
    children.push(
      buildTable(
        table.headers,
        table.rows.map((r) => r.map((v) => (v === null ? '' : String(v)))),
        data.style.brandColor,
        font,
        ar,
      ),
    );
  }

  // Validation report
  if (data.style.includeValidationReport) {
    children.push(p(t.validationReport, { heading: HeadingLevel.HEADING_1 }));
    if (!data.findings.length) {
      children.push(p(t.noFindings));
    } else {
      children.push(
        buildTable(
          [t.severity, t.location, t.finding],
          data.findings.map((f) => [
            t.severityName[f.severity] ?? f.severity,
            [f.sheetName, f.cell].filter(Boolean).join(' / ') || '—',
            ar ? f.messageAr : f.message,
          ]),
          data.style.brandColor,
          font,
          ar,
          data.findings.map((f) => SEVERITY_COLORS[f.severity]),
        ),
      );
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ children: [PageNumber.CURRENT], font })],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}

function buildTable(
  headers: string[],
  rows: string[][],
  brandColor: string,
  font: string,
  rtl: boolean,
  rowColors?: (string | undefined)[],
): Table {
  const cell = (text: string, opts: { header?: boolean; color?: string } = {}): TableCell =>
    new TableCell({
      shading: opts.header ? { fill: brandColor } : undefined,
      children: [
        new Paragraph({
          bidirectional: rtl,
          children: [
            new TextRun({
              text,
              bold: opts.header,
              color: opts.header ? 'FFFFFF' : opts.color,
              font,
              rightToLeft: rtl,
            }),
          ],
        }),
      ],
    });

  const headerCells = headers.map((h) => cell(h, { header: true }));
  const bodyRows = rows.map(
    (r, i) =>
      new TableRow({
        children: r.map((v) => cell(v, { color: rowColors?.[i] })),
      }),
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    visuallyRightToLeft: rtl,
    rows: [new TableRow({ tableHeader: true, children: headerCells }), ...bodyRows],
  });
}
