import type { DocumentData } from './docx-builder';

const esc = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Minimal single-template HTML export sharing DocumentData with the DOCX builder. */
export function buildHtml(data: DocumentData): string {
  const ar = data.language === 'ar';
  const title = ar
    ? data.summary?.titleAr ?? `تقرير التحليل المالي — ${data.fileName}`
    : data.summary?.title ?? `Financial Analysis Report — ${data.fileName}`;
  const paragraphs = ar ? data.summary?.paragraphsAr : data.summary?.paragraphs;

  const tableHtml = (headers: string[], rows: string[][]): string => `
    <table>
      <thead><tr>${headers.map((h) => `<th>${esc(h)}</th>`).join('')}</tr></thead>
      <tbody>${rows
        .map((r) => `<tr>${r.map((v) => `<td>${esc(v)}</td>`).join('')}</tr>`)
        .join('')}</tbody>
    </table>`;

  const sections: string[] = [`<h1>${esc(title)}</h1>`];

  if (paragraphs?.length) {
    sections.push(`<h2>${ar ? 'الملخص التنفيذي' : 'Executive Summary'}</h2>`);
    sections.push(...paragraphs.map((p) => `<p>${esc(p)}</p>`));
  }
  if (data.summary?.keyFigures.length) {
    sections.push(
      tableHtml(
        [ar ? 'المؤشر' : 'Figure', ar ? 'القيمة' : 'Value'],
        data.summary.keyFigures.map((f) => [ar ? f.labelAr : f.label, String(f.value)]),
      ),
    );
  }

  sections.push(`<h2>${ar ? 'الجداول المكتشفة' : 'Detected Tables'}</h2>`);
  for (const t of data.tables) {
    sections.push(`<h3>${esc(t.sheetName)} — ${esc(t.range)}</h3>`);
    sections.push(
      tableHtml(
        t.headers,
        t.rows.map((r) => r.map((v) => (v === null ? '' : String(v)))),
      ),
    );
  }

  sections.push(`<h2>${ar ? 'تقرير التحقق المالي' : 'Financial Validation Report'}</h2>`);
  if (data.findings.length) {
    sections.push(
      tableHtml(
        ar ? ['الخطورة', 'الموقع', 'الملاحظة'] : ['Severity', 'Location', 'Finding'],
        data.findings.map((f) => [
          f.severity,
          [f.sheetName, f.cell].filter(Boolean).join(' / ') || '—',
          ar ? f.messageAr : f.message,
        ]),
      ),
    );
  } else {
    sections.push(`<p>${ar ? 'لم تُرصد أي ملاحظات.' : 'No findings.'}</p>`);
  }

  return `<!doctype html>
<html lang="${data.language}" dir="${ar ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
<style>
  body { font-family: ${ar ? "'Traditional Arabic', 'Amiri', serif" : 'Calibri, sans-serif'}; margin: 2rem auto; max-width: 900px; padding: 0 1rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th { background: #${data.style.brandColor}; color: #fff; }
  th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: ${ar ? 'right' : 'left'}; }
  h1 { color: #${data.style.brandColor}; }
</style>
</head>
<body>
${sections.join('\n')}
<footer><small>${ar ? 'أُنشئ بواسطة منصة الذكاء الاصطناعي لتحليل المستندات المالية' : 'Generated by the AI Financial Document Intelligence Platform'}</small></footer>
</body>
</html>`;
}
